Rust issue solved
arufa-research/polar pull request #20
Opened 2021-09-09 14:22 UTC by hunny98

2021-09-12 15:34 UTC, udit-gulati requested changes

2021-09-12 15:34 UTC, udit-gulati commented on packages/polar/src/lib/compile/checkEnv.ts
> +  } else if (!rustcCurrVersion || semver.lt(rustcCurrVersion, rustcVersion)) {
version not present is already checked above

```suggestion
  } else if (semver.lt(rustcCurrVersion, rustcVersion)) {
```

2021-09-12 15:34 UTC, udit-gulati commented on packages/polar/src/lib/compile/checkEnv.ts
> +  } else if (!cargoCurrVersion || semver.lt(cargoCurrVersion, cargoVersion)) {
version not present is already checked above

2021-09-13 11:53 UTC, coco-sha approved these changes
LGTM

2021-09-13 16:30 UTC, udit-gulati approved these changes

2021-09-13 16:57 UTC, merged